# Generated by Django 3.2.9 on 2021-11-26 14:05

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='Unknown', max_length=50)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Piano',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('brand', models.CharField(default='Unknown', max_length=50)),
                ('title', models.CharField(default='Unknown', max_length=50)),
                ('type', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.FloatField(blank=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000.0)])),
                ('year_of_release', models.DateField(blank=True, null=True)),
                ('genre', models.ManyToManyField(blank=True, null=True, to='Instruments.Genre')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('brand', models.CharField(default='Unknown', max_length=50)),
                ('title', models.CharField(default='Unknown', max_length=50)),
                ('type', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.FloatField(blank=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000.0)])),
                ('year_of_release', models.DateField(blank=True, null=True)),
                ('genre', models.ManyToManyField(blank=True, null=True, to='Instruments.Genre')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Drums',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('brand', models.CharField(default='Unknown', max_length=50)),
                ('title', models.CharField(default='Unknown', max_length=50)),
                ('type', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.FloatField(blank=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000.0)])),
                ('year_of_release', models.DateField(blank=True, null=True)),
                ('genre', models.ManyToManyField(blank=True, null=True, to='Instruments.Genre')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
