# Generated by Django 3.2.9 on 2021-11-26 23:40

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown', max_length=50)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('brand', models.CharField(default='Unknown', max_length=50)),
                ('title', models.CharField(default='Unknown', max_length=50)),
                ('isntrument_type', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000.0)])),
                ('year_of_release', models.DateField(blank=True, null=True)),
                ('genre', models.ManyToManyField(blank=True, to='Instruments.Genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
