# Generated by Django 3.2.9 on 2021-11-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drums',
            name='genre',
            field=models.ManyToManyField(blank=True, to='Instruments.Genre'),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='genre',
            field=models.ManyToManyField(blank=True, to='Instruments.Genre'),
        ),
        migrations.AlterField(
            model_name='piano',
            name='genre',
            field=models.ManyToManyField(blank=True, to='Instruments.Genre'),
        ),
    ]
