# Generated by Django 3.2.9 on 2021-11-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='isntrument_type',
            new_name='instrument_type',
        ),
    ]
