# Generated by Django 3.2.9 on 2021-11-26 14:21

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0002_auto_20211126_1406'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('brand', models.CharField(default='Unknown', max_length=50)),
                ('title', models.CharField(default='Unknown', max_length=50)),
                ('type', models.CharField(blank=True, default='', max_length=50)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('price', models.FloatField(blank=True, default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100000.0)])),
                ('year_of_release', models.DateField(blank=True, null=True)),
                ('genre', models.ManyToManyField(blank=True, to='Instruments.Genre')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='guitar',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='piano',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Drums',
        ),
        migrations.DeleteModel(
            name='Guitar',
        ),
        migrations.DeleteModel(
            name='Piano',
        ),
    ]
