# Generated by Django 3.2.9 on 2021-11-26 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Instruments', '0003_auto_20211126_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='type',
            new_name='isntrument_type',
        ),
    ]
